name: Create PR

on:
  push:
    branches: [ temp/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set environment variables
        run: |
          echo "SHORT_REF=`echo ${{ github.ref }} | cut -d/ -f3-`" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          target_branch: 'main'
          title: '[File Move Test] ${{ env.SHORT_REF }}'
          get_diff: true

      - name: Move files
        run: |
          mv temp2/a.rm temp/a.rm
          mv temp2/b.rm temp/b.rm
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "Move files"
          git push -f -u origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
